### ISSUE TITLE
Questions about code

### ISSUE THREAD

**Issue by sbernatsky** [odnoklassniki/shared-memory-cache#1]
Так как я не зарегистрирован на хабре, то задам вопрос здесь :)

Сначала несколько наблюдений.
1. Попробовал запустить ваш код под ibm jdk 1.7 - заработал. Там тоже NIO использует реализацию sun/oracle
1. Попробовал запустить под 1.6 - не получилось.
   Ошибка: используемый метод sun.misc.Unsafe.copyMemory(Object, long, Object, long, long) появился только в 1.7
2. Поскольку код работает только под 1.7,  и там уже починили багу с ReentrantReadWriteLock (http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6625723), то можно опять вернуться к использованию ReentrantReadWriteLock вместо Semaphore.

Вопрос в следующем.
Зачем надо очищать "хвост" сегмента (purgeOverlappingRegion(segment, tail, segmentSize)) в методе cache.UnsafeMemoryCache.put(long, byte[]) если кешируемые данные все-равно туда не поместятся?
if (newTail > segmentSize) {
    purgeOverlappingRegion(segment, tail, segmentSize);
    tail = DATA_START;
    newTail = (tail + length + 7) & ~7;
}

**Comment by apangin** [comment]
Добрый день.
Спасибо за комментарии.
Метод copyMemory(Object srcBase, long srcOffset, destBase, long 
destOffset, bytes) есть в JDK 6,
начиная с некоторого апдейта. С какого именно - не проверял, но он 
точно есть в 6u23, и его точно нет в 6u13.
Про лишний purgeOverlappingRegion - совершенно справедливое замечание - 
уберу.
Это рудимент, оставшийся от первой версии алгоритма, когда 
непомещающийся блок разбивался на две части, одна из которых шла в конец 
сегмента, а другая в начало.

Спасибо,
   Андрей
